services:
  - type: web
    name: filmila-webapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://filmila-webapp.onrender.com
      - key: API_BASE_URL
        value: https://filmila-webapp.onrender.com/api
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false

  - type: postgresql
    name: filmila-db
    plan: free
    ipAllowList: []
